monitorDwindleOverrides = []
monitorNiriOverrides = []
version = 5

[appearance]
mode = "dark"

[borders]
enabled = false
width = 5.0

[borders.color]
alpha = 1.0
blue = 0.3294942080974579
green = 0.3294942080974579
red = 0.3168213539398634

[dwindle]
defaultSplitRatio = 1.0
moveToRootStable = true
singleWindowAspectRatio = "4:3"
smartSplit = false
splitWidthMultiplier = 1.0
useGlobalGaps = true

[focus]
followsMouse = false
followsWindowToMonitor = false
moveMouseToFocusedWindow = false

[gaps]
size = 8.0

[gaps.outer]
bottom = 8.0
left = 8.0
right = 8.0
top = 8.0

[general]
animationsEnabled = true
defaultLayoutType = "niri"
hotkeysEnabled = true
ipcEnabled = false
preventSleepEnabled = false
updateChecksEnabled = true

[gestures]
fingerCount = 3
invertDirection = true
scrollEnabled = true
scrollModifierKey = "optionShift"
scrollSensitivity = 5.0

[mouseWarp]
axis = "horizontal"
margin = 1

[[mouseWarp.monitorOrder]]
displayId = 5
name = "SAMSUNG"

[[mouseWarp.monitorOrder]]
displayId = 1
name = "Built-in Retina Display"

[niri]
alwaysCenterSingleColumn = true
centerFocusedColumn = "never"
columnWidthPresets = [0.3333333333333333, 0.5, 0.66]
infiniteLoop = false
maxVisibleColumns = 2
maxWindowsPerColumn = 2
singleWindowAspectRatio = "4:3"

[quakeTerminal]
animationDuration = 0.2
autoHide = false
enabled = true
heightPercent = 50.0
monitorMode = "focusedWindow"
opacity = 1.0
position = "center"
useCustomFrame = false
widthPercent = 50.0

[state]
commandPaletteLastMode = "windows"
hiddenBarIsCollapsed = true

[statusBar]
showAppNames = false
showWorkspaceName = false
useWorkspaceId = false

[workspaceBar]
backgroundOpacity = 0.1
deduplicateAppIcons = false
enabled = true
height = 24.0
hideEmptyWorkspaces = false
labelFontSize = 12.0
notchAware = true
position = "overlappingMenuBar"
reserveLayoutSpace = true
showFloatingWindows = false
showLabels = true
windowLevel = "popup"
xOffset = 0.0
yOffset = 0.0

[workspaceBar.accentColor]
alpha = 1.0
blue = -1.0
green = -1.0
red = -1.0

[workspaceBar.textColor]
alpha = 1.0
blue = -1.0
green = -1.0
red = -1.0

[[appRules]]
assignToWorkspace = "1"
bundleId = "com.apple.finder"
id = "7B969BE5-9022-4232-8879-F1A07B68BB2A"
layout = "tile"

[[appRules]]
assignToWorkspace = "2"
bundleId = "com.microsoft.VSCode"
id = "01C03EC4-8935-41C8-9BF3-3E9732A51FCB"
layout = "tile"

[[appRules]]
assignToWorkspace = "3"
bundleId = "com.apple.Terminal"
id = "30D88116-DE9C-4C4A-AE63-34B4C3466122"
layout = "tile"

[[appRules]]
assignToWorkspace = "1"
bundleId = "com.apple.python3"
id = "2F960DBE-8D4C-4D79-99D4-99BAD8A5394A"
layout = "float"

[[appRules]]
assignToWorkspace = "3"
bundleId = "com.mitchellh.ghostty"
id = "5F207F18-CA49-4F0D-9924-516801397A6E"
layout = "tile"

[[appRules]]
assignToWorkspace = "3"
bundleId = "com.cmuxterm.app"
id = "130EB6A6-D995-4F30-B696-AD9CD1D7E750"
layout = "tile"

[[appRules]]
assignToWorkspace = "4"
bundleId = "com.hnc.Discord"
id = "83553E2D-DD1D-4BB7-A5B3-0214A3E1C26F"
layout = "tile"

[[appRules]]
assignToWorkspace = "4"
bundleId = "com.apple.Safari"
id = "F0302051-39EB-4241-80D4-AF56DED00360"

[[appRules]]
assignToWorkspace = "4"
bundleId = "com.microsoft.edgemac"
id = "D7B04F16-950E-4465-99F2-CF023ACFD2A3"

[[appRules]]
assignToWorkspace = "4"
bundleId = "com.highcaffeinecontent.radio"
id = "39FECBC7-5406-4132-BC65-7F9AD1859F5B"
layout = "tile"

[[appRules]]
assignToWorkspace = "3"
bundleId = "ai.opencode.desktop"
id = "E05D741C-2FE5-4B0F-91D7-4272E78B5FE1"
layout = "tile"

[[appRules]]
assignToWorkspace = "4"
bundleId = "com.brave.Browser"
id = "1C8C13B4-02C9-4582-B686-97736AC3A039"
layout = "tile"

[[appRules]]
assignToWorkspace = "4"
bundleId = "com.microsoft.teams2"
id = "902F864D-DBAD-4F79-9BA5-0F4066D0FC05"
layout = "tile"

[[appRules]]
assignToWorkspace = "3"
bundleId = "com.github.GitHubClient"
id = "432CC75F-C644-4DAC-89DD-A933573D432D"
layout = "tile"

[[appRules]]
assignToWorkspace = "3"
bundleId = "com.sourcegit-scm.sourcegit"
id = "03A58F6F-B779-4DEE-8F6C-FB2216A7C1FF"
layout = "tile"

[[appRules]]
assignToWorkspace = "4"
bundleId = "com.reactotron.app"
id = "89DA6D53-F470-43CD-A5B5-08D14C110B53"
layout = "tile"

[[appRules]]
assignToWorkspace = "4"
bundleId = "com.google.Chrome.app.cifhbcnohmdccbgoicgdjpfamggdegmo"
id = "19D25767-E2AA-454A-B49B-5872104AD5E1"
layout = "tile"

[[hotkeys]]
binding = "Option+1"
id = "switchWorkspace.0"

[[hotkeys]]
binding = "Option+Shift+1"
id = "moveToWorkspace.0"

[[hotkeys]]
binding = "Option+2"
id = "switchWorkspace.1"

[[hotkeys]]
binding = "Option+Shift+2"
id = "moveToWorkspace.1"

[[hotkeys]]
binding = "Option+3"
id = "switchWorkspace.2"

[[hotkeys]]
binding = "Option+Shift+3"
id = "moveToWorkspace.2"

[[hotkeys]]
binding = "Option+4"
id = "switchWorkspace.3"

[[hotkeys]]
binding = "Option+Shift+4"
id = "moveToWorkspace.3"

[[hotkeys]]
binding = "Unassigned"
id = "switchWorkspace.4"

[[hotkeys]]
binding = "Unassigned"
id = "moveToWorkspace.4"

[[hotkeys]]
binding = "Unassigned"
id = "switchWorkspace.5"

[[hotkeys]]
binding = "Unassigned"
id = "moveToWorkspace.5"

[[hotkeys]]
binding = "Unassigned"
id = "switchWorkspace.6"

[[hotkeys]]
binding = "Unassigned"
id = "moveToWorkspace.6"

[[hotkeys]]
binding = "Unassigned"
id = "switchWorkspace.7"

[[hotkeys]]
binding = "Unassigned"
id = "moveToWorkspace.7"

[[hotkeys]]
binding = "Unassigned"
id = "switchWorkspace.8"

[[hotkeys]]
binding = "Unassigned"
id = "moveToWorkspace.8"

[[hotkeys]]
binding = "Control+Option+Tab"
id = "workspaceBackAndForth"

[[hotkeys]]
binding = "Unassigned"
id = "switchWorkspace.next"

[[hotkeys]]
binding = "Unassigned"
id = "switchWorkspace.previous"

[[hotkeys]]
binding = "Command+Left Arrow"
id = "focus.left"

[[hotkeys]]
binding = "Command+Down Arrow"
id = "focus.down"

[[hotkeys]]
binding = "Command+Up Arrow"
id = "focus.up"

[[hotkeys]]
binding = "Command+Right Arrow"
id = "focus.right"

[[hotkeys]]
binding = "Unassigned"
id = "focusPrevious"

[[hotkeys]]
binding = "Unassigned"
id = "focusDownOrLeft"

[[hotkeys]]
binding = "Unassigned"
id = "focusUpOrRight"

[[hotkeys]]
binding = "Control+Option+Shift+Up Arrow"
id = "moveWindowToWorkspaceUp"

[[hotkeys]]
binding = "Control+Option+Shift+Down Arrow"
id = "moveWindowToWorkspaceDown"

[[hotkeys]]
binding = "Control+Option+Shift+Page Up"
id = "moveColumnToWorkspaceUp"

[[hotkeys]]
binding = "Control+Option+Shift+Page Down"
id = "moveColumnToWorkspaceDown"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.0"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.1"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.2"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.3"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.4"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.5"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.6"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.7"

[[hotkeys]]
binding = "Unassigned"
id = "moveColumnToWorkspace.8"

[[hotkeys]]
binding = "Control+Shift+Left Arrow"
id = "move.left"

[[hotkeys]]
binding = "Control+Shift+Down Arrow"
id = "move.down"

[[hotkeys]]
binding = "Control+Shift+Up Arrow"
id = "move.up"

[[hotkeys]]
binding = "Control+Shift+Right Arrow"
id = "move.right"

[[hotkeys]]
binding = "Option+Command+Tab"
id = "focusMonitorNext"

[[hotkeys]]
binding = "Unassigned"
id = "focusMonitorPrevious"

[[hotkeys]]
binding = "Control+Command+`"
id = "focusMonitorLast"

[[hotkeys]]
binding = "Option+Return"
id = "toggleFullscreen"

[[hotkeys]]
binding = "Unassigned"
id = "toggleNativeFullscreen"

[[hotkeys]]
binding = "Control+Left Arrow"
id = "moveColumn.left"

[[hotkeys]]
binding = "Control+Right Arrow"
id = "moveColumn.right"

[[hotkeys]]
binding = "Option+T"
id = "toggleColumnTabbed"

[[hotkeys]]
binding = "Option+Home"
id = "focusColumnFirst"

[[hotkeys]]
binding = "Option+End"
id = "focusColumnLast"

[[hotkeys]]
binding = "Control+Option+1"
id = "focusColumn.0"

[[hotkeys]]
binding = "Control+Option+2"
id = "focusColumn.1"

[[hotkeys]]
binding = "Control+Option+3"
id = "focusColumn.2"

[[hotkeys]]
binding = "Control+Option+4"
id = "focusColumn.3"

[[hotkeys]]
binding = "Control+Option+5"
id = "focusColumn.4"

[[hotkeys]]
binding = "Control+Option+6"
id = "focusColumn.5"

[[hotkeys]]
binding = "Control+Option+7"
id = "focusColumn.6"

[[hotkeys]]
binding = "Control+Option+8"
id = "focusColumn.7"

[[hotkeys]]
binding = "Control+Option+9"
id = "focusColumn.8"

[[hotkeys]]
binding = "Shift+Command+Right Arrow"
id = "cycleColumnWidthForward"

[[hotkeys]]
binding = "Shift+Command+Left Arrow"
id = "cycleColumnWidthBackward"

[[hotkeys]]
binding = "Shift+Command+Up Arrow"
id = "toggleColumnFullWidth"

[[hotkeys]]
binding = "Shift+Command+Down Arrow"
id = "balanceSizes"

[[hotkeys]]
binding = "Unassigned"
id = "moveToRoot"

[[hotkeys]]
binding = "Unassigned"
id = "toggleSplit"

[[hotkeys]]
binding = "Unassigned"
id = "swapSplit"

[[hotkeys]]
binding = "Unassigned"
id = "resizeGrow.left"

[[hotkeys]]
binding = "Unassigned"
id = "resizeGrow.right"

[[hotkeys]]
binding = "Unassigned"
id = "resizeGrow.up"

[[hotkeys]]
binding = "Unassigned"
id = "resizeGrow.down"

[[hotkeys]]
binding = "Unassigned"
id = "resizeShrink.left"

[[hotkeys]]
binding = "Unassigned"
id = "resizeShrink.right"

[[hotkeys]]
binding = "Unassigned"
id = "resizeShrink.up"

[[hotkeys]]
binding = "Unassigned"
id = "resizeShrink.down"

[[hotkeys]]
binding = "Unassigned"
id = "preselect.left"

[[hotkeys]]
binding = "Unassigned"
id = "preselect.right"

[[hotkeys]]
binding = "Unassigned"
id = "preselect.up"

[[hotkeys]]
binding = "Unassigned"
id = "preselect.down"

[[hotkeys]]
binding = "Unassigned"
id = "preselectClear"

[[hotkeys]]
binding = "Option+Tab"
id = "openCommandPalette"

[[hotkeys]]
id = "raiseAllFloatingWindows"

[hotkeys.binding]
keyCode = 10
modifiers = 512

[[hotkeys]]
binding = "Unassigned"
id = "rescueOffscreenWindows"

[[hotkeys]]
binding = "Control+Shift+F"
id = "toggleFocusedWindowFloating"

[[hotkeys]]
binding = "Unassigned"
id = "assignFocusedWindowToScratchpad"

[[hotkeys]]
binding = "Unassigned"
id = "toggleScratchpadWindow"

[[hotkeys]]
binding = "Control+Option+M"
id = "openMenuAnywhere"

[[hotkeys]]
binding = "Control+Shift+B"
id = "toggleWorkspaceBarVisibility"

[[hotkeys]]
binding = "Unassigned"
id = "toggleHiddenBar"

[[hotkeys]]
binding = "Control+Shift+T"
id = "toggleQuakeTerminal"

[[hotkeys]]
binding = "Option+Shift+L"
id = "toggleWorkspaceLayout"

[[hotkeys]]
binding = "Control+Up Arrow"
id = "toggleOverview"

[[monitorBarOverrides]]
id = "E85AE3EF-FD20-40AB-A2FE-5A11A3C42A6C"
monitorDisplayId = 5
monitorName = "SAMSUNG"
reserveLayoutSpace = false

[[monitorOrientationOverrides]]
monitorDisplayId = 5
monitorName = "SAMSUNG"
orientation = "horizontal"

[[workspaces]]
id = "AD36F001-C57E-41A5-AC1D-DF5249D007F0"
layoutType = "niri"
name = "1"

[workspaces.monitorAssignment]
type = "main"

[[workspaces]]
id = "454CECD4-5E9D-4ED1-95D7-979D48817F5F"
layoutType = "niri"
name = "2"

[workspaces.monitorAssignment]
type = "main"

[[workspaces]]
id = "BEB842B5-E894-4791-9FD1-397C3CDD3538"
layoutType = "niri"
name = "3"

[workspaces.monitorAssignment]
type = "main"

[[workspaces]]
id = "248AA883-2261-4D45-943C-79C0E46A232B"
layoutType = "niri"
name = "4"

[workspaces.monitorAssignment]
type = "secondary"
